### ISSUE TITLE
Toggle between "add connection" and "normal" mode

### ISSUE THREAD

**Issue by Labauke** [ghorwin/MasterSim#27]
Es wäre nutzerfreundlich wenn man nicht bei jeder Verbindung neu auf den "Verbinde Ein/Ausgänge" Button drücken muss, sondern stattdessen in einen "Verbindungsmodus" geschaltet wird in dem man beliebig viele Verbindungen machen kann.

**Comment by ghorwin** [comment]
Ließe sich umsetzen, wenn man nach Abschluss einer Verbindung automatisch wieder in den Verbindungsmodus springt, bis man diesen verlässt.

**Comment by Labauke** [comment]
Eine Möglichkeit gibt es noch: Der Verbindungsmodus wird immer dann aktiviert wenn ich in die Nähe eines Sockets klicke. Dann brauche ich eigentlich gar kein Umschalten mehr zwischen verschiedenen Modi. Slaves und Connections kann ich weiter verschieben wenn ich eben in deren Nähe klicke, wie bisher.
So ist es übrigens auch in Modelica :)

**Comment by ghorwin** [comment]
Das klingt sinnvoll, so können wir das machen.
