### ISSUE TITLE
show and edit factor, offset and devider in graphical connection mode

### ISSUE THREAD

**Issue by Labauke** [ghorwin/MasterSim#28]
In der Praxis wäre das extrem hilfreich und verhindert Fehler:
Die Umrechnug von Größen wird in der grafischen "Slave-Connection" Ansicht für jede Verbindung gezeigt (eine Box auf jeder Verbindungslinie) und kann wenn möglich editiert werden. Dabei gibt es zusätzlich zu `Factor` und `Offset` auch `Devider`. Der kann zwar durch Factor ausgedrückt werden, ist aber dann nicht mehr nachvollziehbar (wenn ich z.B. den Massensatrom auf 23 Rohre aufteile).

**Comment by ghorwin** [comment]
Automatische Platzierung von Connector-Attribut-Labels ist nicht ganz trivial. Vielleicht macht man auch nur in der Mitte eines Konnektors eine kleine Box, sobald Factor/Offset/Divider angegeben ist und wenn man mit der Maus darüber fährt, sieht man die Umrechnungsformel?

**Comment by Labauke** [comment]
Ja das klingt gut. Ich habe auch gestern mal kurz reingeschaut, man könnte immer das mittlere ConnectorSegment nutzen.

**Comment by Labauke** [comment]
Was vielleicht noch besser bedienbar ist: Faktor, Offset, Divider werden in dem Parameter TableWidget links unten gezeigt wenn die Verbindung ausgewählt ist. Dann könnte man dort auch gleich editieren. Das wäre meine Wunschvariante.

**Comment by ghorwin** [comment]
TODO:

- Nach Änderung eines Connector-Attributs müsste entweder der Connector neu ausgewählt werden, oder das Connector-Fenster müsste geschlossen werden: grundsätzlich sollte das Attribut-Fenster mit der aktuellen Auswahl synchronisiert werden, also auch bei Abwahl des Connectors, laden eines neuen Projekts, löschen eines Connectors im "Connection View" etc.; sonst besteht die Möglichkeit, eine Eingabe im Connector-Property-Widget zu machen für einen Connector, den es nicht mehr gibt -> **CRASH**

- neue Connector-Attribute (Linienstärle+Farbe) müssen in der Projektdatei gespeichert werden, codiert in der "graph" Zeile -> eventuell mal über eine Änderung in eine XML-Datei nachdenken...

**Comment by Labauke** [comment]
`Nach Änderung eines Connector-Attributs müsste entweder der Connector neu ausgewählt werden, oder das Connector-Fenster müsste geschlossen werden`

Beides schwierig: Nach dem Ändern eines Attributs möchte ich ja noch andere Attribute ändern können, deshalb kann das Fenster nicht geschlossen werden. Wenn ich den Connector neu auswähle, sehe ich die Änderungen (Farbe, equation box) nicht. 

Mein Vorschlag: in `MSIMViewSlaves::onModified` entsprechend reagieren. Wenn es der `m_selectedEdgeIdx` nicht mehr existiert, dann werden die SlaveParameter gezeigt.

**Comment by ghorwin** [comment]
`MSIMViewSlaves::onModified()` ist für Änderungen im Projekt: Auswahl ist keine Projekteigenschaft sondern ein unabhängiger Oberflächenzustand.
