### ISSUE TITLE
CRASH beim "auswählen eines Connectors" ohne vorherige Verschiebung eines Connectors/Slaves

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/MasterSim#31]
Zum Reproduzieren der Schritte:

1. Projektdatei laden
2. in Scene auf einen Konnektor klicken, diesen aber nicht verschieben
3. Maustaste loslassen -> **CRASH**

**Comment by Labauke** [comment]
Unter Windows gibt es hier keinen Crash.

**Comment by ghorwin** [comment]
Ja, Linux-spezifisch: Event-Loop und "update()" call der GraphicsScene prüfen...
