### ISSUE TITLE
Avoid crash after removing connection

### ISSUE THREAD

**Issue by Labauke** [ghorwin/MasterSim#35]
- Connection im slave view auswählen
- im die connection im connection view löschen
- zurück in den slave view wechseln
Die connection wird noch angezeigt und beim Bearbeiten gibt es einen crash

Hatte ich schon verhindert, bitte den Code nicht wieder löschen.

**Comment by ghorwin** [comment]
Löschen einer Verbindung löst eine Undo-Action aus -> d.h. in onModified() des Slave-View müsste bei einer solchen Aktion auch die Connection im BlockMod gelöscht werden

**Comment by Labauke** [comment]
Wird sie ja auch, aber deren Eigenschaften im property table widget werden noch angezeigt
