### ISSUE TITLE
Save project with Strg+S does not work

### ISSUE THREAD

**Issue by Labauke** [ghorwin/MasterSim#36]

**Comment by ghorwin** [comment]
Liegt das am Fokus? Geht es, wenn man in den Navigationsbaum geklickt hat?

**Comment by ghorwin** [comment]
WICHTIG: Prüfen, warum die automatisch angelegten Shortcuts via ui-File nicht mehr funktionieren. Hat jemand das MainWindow-Ui-File kaputt gemacht oder warum gehen die Action-Shortcuts nicht mehr?

**Comment by Labauke** [comment]
Das gleiche Problem hatten wir im SIM-VICUS auch schon. Da haben wir das auch im cpp nochmal definiert, dann gings. unter Linux gab es das Problem nicht.

**Comment by ghorwin** [comment]
Vielleicht ein Qt Bug?
