### ISSUE TITLE
implement export of project package according to SSP standard

### ISSUE THREAD

**Issue by Labauke** [ghorwin/MasterSim#37]
Wurde auch schon ab und zu nachgefragt

**Comment by ghorwin** [comment]
Ist ein Convenience-Feature: wenn man die msim-Datei und die dazugehörigen fmu-Dateien in einem Wurzel-Verzeichnis hält, kann man dieses einfach in eine 7z-Datei schieben und hat so auch ein Project-Package.

Das Programmieren von Import/Export (also via zlib packen) hat wie auch beim SPP oder FMUs das Problem, dass Umlaute in Dateinamen zu Problemen führen (zip-Format kennt keine Zeichentabellen).
Daher die Empfehlung, ein geeignetes Packformat (7z, tgz etc.) zu wählen und selbst die Verzeichnishierarchie zu packen.

**Comment by ghorwin** [comment]
SSP-Standard-Export sollte nicht zu schwer sein, da MasterSim nur eine Hierarchieebene unterstützt. Man müsste mal ein xml-Vorlage machen, die in der SSP-Arbeitsgruppe prüfen und dann basierend auf so einer Vorlage den Export bauen.

**Comment by ghorwin** [comment]
Geschlossen als Duplikat von #13
