### ISSUE TITLE
Add a checkbox "skip-unzip" in UI to add --skip-unzip to command line and disable manual editing of command line in GUI

### ISSUE THREAD

**Issue by HarimLee-kr** [ghorwin/MasterSim#40]
https://github.com/ghorwin/MasterSim/blob/3be5e19fa4559d7e26450986d95755a53a24fef3/MasterSimulatorUI/src/MSIMViewSimulation.cpp#L186C28-L186C28

Environment : Window x86(64bit)

I want to use '--skip-unzip' option. But the reset fuction 'm_commandLineArgs.clear();' works everytime before simulation.
I could not apply the option. so I used commandline at terminal(cmd) added '--skip-unzip'
But when I use that in terminal, there are no change with 'results.csv' even i changed the 'tEnd' in 'simultion time frame' setting

I think have to add something like 'user's commandline' that user can change commandline and start with that
While maintaining the 'default commandline' button

**Comment by ghorwin** [comment]
Hi, 

the purpose of the GUI-generated command line is to copy it into a terminal and execute the MasterSimulator solver directly (or via script). Actually, editing the command line in the GUI is not meaningful (and should therefore not be possible).

I'll fix the editing capability in the next release and add a checkbox "skip-unzip" in the UI window.

Until then you can just copy the command line and run the MasterSimulator from terminal/command line window.

**Comment by HarimLee-kr** [comment]
Thanks your response!

Could I ask something?
I said that 'But when I use that in terminal, there are no change with 'results.csv' even i changed the 'tEnd' in 'simultion time frame' setting'
i checked it works commandline on terminal that change the 'tEnd' setting

but i don't know why still don't apply the modelDescription.xml change in simulation.
I did change modelDescription.xml of the example project(LV_Richardson_noiter.msim)
![image](https://github.com/ghorwin/MasterSim/assets/67570225/e79bbd0c-4a53-4d1d-b39e-53a8106ce548)
the changes are ( I changed all .xml file, predetor and prey)
``` <Real start="10.0"/> ```
to
``` <Real start="20.0"/>```
so I expected the simulation result change to start '20', not '10'
but there are no changes in the result
the log is it
![image](https://github.com/ghorwin/MasterSim/assets/67570225/b1c7a2b0-6b4d-464c-8977-495f3118ceae)

you can see the third line " (Real)   y=20.0 " and fifth line "(Real)   x=20.0"
but still "Initial condition iteration" not change.

in my opinion, the start value is defined in .dll file so i can apply the change of modeldescription, is it right?

**Comment by ghorwin** [comment]
Hi, let's move the discussion about the "start" value to another thread. Just to clarify: you just change the start-attribute in the xml-description and re-run the simulator. This should indeed update the start value in the simulation, as the hard-coded start-value inside the c++ code (which ends up in the dll) will be overwritten once the initial condition calculation is through.

Let me try this first myself, then - if this is indeed a bug - i'll open another ticket.
