### ISSUE TITLE
Support UTF-8 in project path

### ISSUE THREAD

**Issue by Labauke** [ghorwin/MasterSim#42]
Super nervig! Wenn im Pfad ein "ö" oderso ist, funktioniert nichts mehr. Bis man dahinter kommt woran es liegt, kann das ganz schön dauern...

**Comment by ghorwin** [comment]
Scheint ein Windows-Problem zu sein - unter Linux mit UTF8 geht alles. Welcher Compiler? VC müsste mit Unicode-Pfaden auch umgehen können.

Beim Starten des Subprozesses für die Kommandozeile muss man unter Windows ggfs. in die richtige CP der aktuellen Sprache konvertieren.

**Comment by ghorwin** [comment]
Probleme:

UI - MinGW32 -> Schlägt in Project::write() fehl, d.h. Zeile:

```c++
out.open(prjFile.c_str());
```

funktioniert nicht, wenn prjFile Umlaute enthält. Mit VC2019 geht's. Das ist ein bekanntest MinGW32 Problem, da hier ein wstring overload angeboten ist. Workaround ist, statt der wstring-Variante von open() zuerst den unicode-string in die lokale Zeichenkodierung umzuwandeln (**TODO #1**).

Im Solver wird beim Entpacken einer FMU in `FMU::unzipFMU()` auch einfach der utf8-kodierte Pfad als Argument für miniunz übergeben -> hier muss unabhängig vom Compiler zwingend die lokale Zeichenkodierung verwendet werden (**TODO #2**).

**Comment by ghorwin** [comment]
Funktioniert jetzt mit VC unter Windows. Für MinGW sind noch kleinere Anpassungen notwendig, hat aber erstmal keine Priorität. Debuggen von Dateien mit Unicode-behafteten Zeichen unter Windows im Qt Creator funktioniert nicht --> unter Linux debuggen oder keine Umlaute in msim-Pfad und fmu-Pfaden verwenden!
